### ISSUE TITLE
Chapter 3 aws lambda invoke error

### ISSUE THREAD

**Issue by phersh** [symphoniacloud/programming-aws-lambda-book#5]
When I run this command as written:

```
aws lambda invoke \
  --invocation-type Event \
  --function-name HelloWorldJava \
  --payload \"world\" outputfile.txt
```
I get the error:
`Invalid base64: ""world""`

I'm on a Mac using iterm/zsh. I've tried using base64 to encode the payload but I can't quite get the syntax right.

**Comment by mikebroberts** [comment]
Hi Phil,

Thanks for the question! It looks like this is a new incompatibility with AWS CLI V2 . If you add`--cli-binary-format raw-in-base64-out` as another argument you should find that this works.

I'm going to bring this up with the AWS team since this actually breaks their CLI documentation at https://docs.aws.amazon.com/cli/latest/reference/lambda/invoke.html too, and I wonder if this is something that will get rolled back.

Cheers,

Mike

**Comment by mikebroberts** [comment]
I checked with AWS, and this is a known breaking change. They have a separate CLI page for Lambda when using CLI V2 (https://awscli.amazonaws.com/v2/documentation/api/latest/reference/lambda/invoke.html)

I've started an Errata page in this repo (https://github.com/symphoniacloud/programming-aws-lambda-book/blob/master/ERRATA.md)

Thanks again, and I hope you enjoy the rest of the book.

Mike
