### ISSUE TITLE
Logical Resource Names in end to end tests

### ISSUE THREAD

**Issue by asunar** [symphoniacloud/programming-aws-lambda-book#9]
What do you think about retrieving the logical resource id from the template.yaml file? 

For example, "PipelineStartBucket" below
https://github.com/symphoniacloud/programming-aws-lambda-book/blob/1640f7d0bb222c96ab98a03702624d64ac05e0d0/chapter6/integration-tests/src/test/java/book/pipeline/PipelineIT.java#L37

can come from template.yaml
https://github.com/symphoniacloud/programming-aws-lambda-book/blob/1640f7d0bb222c96ab98a03702624d64ac05e0d0/chapter6/template.yaml#L12

**Comment by mikebroberts** [comment]
We could, although I probably wouldn't for a couple of reasons:

1 - We still need to be able to find the logical name, and how would we do that? In this particular case we could just find the one S3 bucket, but that doesn't feel great as a general solution. This is my main reason why I wouldn't.

2 - Also we can run this test in an environment where the template does exist. For example we could zip / JAR up everything in the integration-tests module and run it from a CI environment, and assuming the stack has been deployed the tests wouldn't need access to the template. For example if we were using CodePipeline there may be a CloudFormation task to deploy the test stack (rather than using the code in the maven definition), and then a CodeBuild task to run the tests.

The flip side is that we do need to know the name of the bucket, and I'll admit there's some duplication there. As an alternative - since we programmatically generate the physical name of the bucket in the template we could replicate that string generation in the test, and then we wouldn't have to do the lookup at all.
